style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: <%- repository_url %>

options:
  commits:
    filters:
      Type:
        - add
        - change
        - deprecate
        - remove
        - fix
        - refactor
        - bump
        - release
    sort_by: Scope

  commit_groups:
    group_by: Type
    sort_by: Title
    title_maps:
      add: Added
      change: Changed
      deprecate: Deprecations
      remove: Removed
      fix: Fixed
      bump: Bumped
      refactor: Refactored

  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject

  issues:
      prefix:
        - #

  refs:
    actions:
      - Closes
      - Fixes
      - Fix

  reverts:
    pattern: "^Revert \"([\\s\\S]*)\"$"
    pattern_maps:
      - Header

  notes:
    keywords:
      - BREAKING CHANGE
