version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_assignees:
      - mech-pig
    default_labels:
      - "dependencies"
    commit_message:
      prefix: "chore"
      include_scope: true
